$schema: https://json-schema.org/draft/2020-12/schema
$id: SystemConfig.yaml
type: object
properties:
  autoUpdate:
    type: boolean
    default: true
    description: CLI auto-update preference
  logLevel:
    type: string
    default: info
    description: Log level for CLI output
required:
  - autoUpdate
  - logLevel
description: System configuration
